export const SET_LOGIN_FLAG = "SET_LOGIN_FLAG";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_AUTHTOKEN = "SET_USER_AUTHTOKEN";
export const CLEAR_AUTH = "CLEAR_AUTH";
export const LOGIN_REQUEST = "LOGIN_REQUEST"
